#!/bin/bash
# Script for uninstall darknexus tools

# ----- darknexus Team -----

#

# Coded by: CRO-THEHACKER

#  * https://github.com/CRO-THEHACKER/

# Feel free to share any ideas with the
# project!
#
# -------------------------

clear

echo "

";

if [ "$PREFIX" = "/data/data/com.termux/files/usr" ]; then

    INSTALL_DIR="$PREFIX/usr/share/doc/darknexus"

    BIN_DIR="$PREFIX/bin/"

    BASH_PATH="$PREFIX/bin/bash"

    TERMUX=true

elif [ "$(uname)" = "Darwin" ]; then

    INSTALL_DIR="/usr/local/darknexus"

    BIN_DIR="/usr/local/bin/"

    BASH_PATH="/bin/bash"

    TERMUX=false

else

    INSTALL_DIR="$HOME/.darknexus"

    BIN_DIR="/usr/local/bin/"

    BASH_PATH="/bin/bash"

    TERMUX=false

fi

echo "[✔] Checking directories...";

if [ -d "$INSTALL_DIR" ]; then

        rm -rf "$INSTALL_DIR"

        rm "$BIN_DIR/darknexus*"

        sudo rm -rf "$INSTALL_DIR"

        sudo rm "$BIN_DIR/darknexus*"

    else

        echo "[✘] If you want to uninstall you must remove previous installations [✘] ";

        echo "[✘] Failed! [✘] ";

fi

echo "[✔] Cleaning up old directories...";

if [ -d "$ETC_DIR/darknexus11" ]; then

    echo "$DIR_FOUND_TEXT"

    if [ "$TERMUX" = true ]; then

        rm -rf "$ETC_DIR/darknexus11"

    else

        sudo rm -rf "$ETC_DIR/darknexus11"

    fi

fi

clear

clear

echo "[✔] all good!"
